Add rss link to page template
utahplt/utahplt.github.io pull request #1
Opened 2024-07-14 16:50 UTC by dominicmkennedy

2024-07-15 16:52 UTC, bennn requested changes
looks good but please undo all the whitespace changes

these diffs seem WAY bigger than they need to be

2024-07-15 17:25 UTC, dominicmkennedy commented
Whoopsie, I think my editor just got a little overzealous with the auto-format. Should be fixed now

2024-07-16 19:55 UTC, bennn commented on 2023/06/gtp-benchmarks-for-gradual-typing-performance.html
> -  ....</code></pre></div>
guess i should finally install pygments :)

2024-07-16 19:55 UTC, merged

2024-07-16 19:56 UTC, bennn reviewed
excellent, thanks!!!!

2024-07-16 21:01 UTC, ashton314 commented
RSS FTW! 🙌🏼